export const EVENTS = {
  connection: 'connection',
  CLIENT: {
    SEND_FIRST_MESSAGE: 'SEND_FIRST_MESSAGE',
    SEND_ROOM_MESSAGE: 'SEND_ROOM_MESSAGE',
    JOIN_ROOM: 'JOIN_ROOM',
  },
  SERVER: {
    JOINED_ROOM: 'JOINED_ROOM',
    RECEIVED_FIRST_MESSAGE: 'RECEIVED_FIRST_MESSAGE',
    RECEIVED_ROOM_MESSAGE: 'RECEIVED_ROOM_MESSAGE',
    STATUS: {
      ONLINE: 'ONLINE',
      OFFLINE: 'OFFLINE',
    },
  },
};
